import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

function parseEnvFile(filePath) {
  try {
    return Object.fromEntries(
      readFileSync(filePath, 'utf8')
        .split('\n')
        .filter(line => line && !line.startsWith('#') && line.includes('='))
        .map(line => {
          const [key, ...rest] = line.split('=');
          return [key.trim(), rest.join('=').trim()];
        })
    );
  } catch {
    return {};
  }
}

const env = {
  ...parseEnvFile(resolve(root, '.env')),
  ...parseEnvFile(resolve(root, '.env.local')),
};

const get = key => env[key] ?? process.env[key] ?? '';

const content = `// Auto-generated by scripts/set-env.mjs — do not edit
export const environment = {
  publicUrl:   '${get('VITE_PUBLIC_URL')}',
  photoUrl:    '${get('VITE_PHOTO_URL')}',
  whatsappUrl: '${get('VITE_WHATSAPP_URL')}',
  githubUrl:   '${get('VITE_GITHUB_URL')}',
  linkedinUrl: '${get('VITE_LINKEDIN_URL')}',
};
`;

const outDir = resolve(root, 'src', 'environments');
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'environment.ts'), content);
console.log('✔ src/environments/environment.ts generated');
